<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>UserConnectionLib</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ServerExceptionLib\ServerExceptionLib.csproj" />
    <ProjectReference Include="..\ServerParametresLib\ServerParametresLib.csproj" />
  </ItemGroup>
</Project>