<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>ClientConnectionLib</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ErrorsProcessingLib\ErrorsProcessingLib.csproj" />
    <ProjectReference Include="..\ParametresLib\ParametresLib.csproj" />
  </ItemGroup>
</Project>