<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Messenger_Client</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ClientConnectionLib\ClientConnectionLib.csproj" />
    <ProjectReference Include="..\..\ErrorsProcessingLib\ErrorsProcessingLib.csproj" />
    <ProjectReference Include="..\..\ParametresLib\ParametresLib.csproj" />
    <ProjectReference Include="..\..\ServerInterfaceLib\ServerInterfaceLib.csproj" />
  </ItemGroup>
</Project>
